### ISSUE TITLE
Many commands do not display the API error

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/uaa-cli#13]
Many commands do not pass back the UAA API error, and require the user to run the command again with `--verbose`.

Instead, if a UAA API error is returned could all commands please return the error without requiring `--verbose`?

**Comment by dbeneke** [comment]
Hello, a number of improvements have been made to the common commands to better communicate the underlying API error.  Please take a look at a recent release and let us know if you find that any one command is still causing issue.  Additionally, --verbose wasn't functional for several of the commands.  We believe we've cleaned up most of those occurrences as well.  The recent 0.10.0 (and prior releases) should include many of these changes.
