### ISSUE TITLE
uaa remove-member

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/uaa-cli#16]
The `uaa add-member` method does not have a corresponding `uaa remove-member` method yet.

**Comment by drnic** [comment]
WIP in go-uaa at https://github.com/cloudfoundry-community/go-uaa/pull/7; requires uaa-cli to be upgraded to v0.0.9 but that involves breaking changes :/

**Comment by dbeneke** [comment]
This command was added in v0.6.0.
