### ISSUE TITLE
issue exsiting https://github.com/cloudfoundry-community/go-uaa/issues/10

### ISSUE THREAD

**Issue by strehle** [cloudfoundry-incubator/uaa-cli#23]
create this issue because finally uaa-cli cannot create context with clients in uaa where a special character is in secret.

Thus, uaa-cli use go-uaa use oauth2 from go, it will be hard to solve.
Issue in go-uaa is https://github.com/cloudfoundry-community/go-uaa/issues/10

From my point of view https://github.com/cloudfoundry-community/go-uaa/issues/10 should be solved but technically you can do a workaround here, therefore an extra issue here

**Comment by strehle** [comment]
with https://github.com/cloudfoundry-incubator/uaa-cli/pull/24 the authentication of clients are not set to header but to body and then no extra urlencode.

**Comment by andrewedstrom** [comment]
Client secret encoding has now been fixed in UAA and the CLI
