### ISSUE TITLE
ETA for next burst of R&D on this CLI?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/uaa-cli#30]
This CLI is obviously a wonderful future direction for UAA administration. Its so much nicer than `cf-uaac` to install and use. Is there an ETA for when a new burst of R&D, curation of issues & PRs, and with new releases, might occur?

**Comment by aegershman** [comment]
I love this CLI. I'm honestly _in_ love with it, which I know is weird and morally questionable, but alas-- it's just that good. I'd be down to help open PRs here and there against docs repos which reference `uaac` and update them to reference this `uaa`. But I guess it's contingent on whether this will become the go-forward strategy for interfacing with UAA.

**Comment by drnic** [comment]
@aramprice will `uaa` CLI get more love this year?

**Comment by Birdrock** [comment]
@drnic Hi Dr. Nic; the UAA team has resumed work on this CLI going forward. Keep an eye out for active development!

**Comment by drnic** [comment]
Awesome news @Birdrock
