### ISSUE TITLE
Remove "experimental" from project description

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-incubator/uaa-cli#32]
In order to promote the usage of the golang uaa-cli, consider removing the word "Experimental" in the part of the project description's "Experimental CLI for UAA written in Go."

*and from the README.md

👍

**Comment by joshuatcasey** [comment]
This sounds doable. I'm checking with the PMs first though.

**Comment by dbeneke** [comment]
Hello @aegershman, I've made some updated to the repo and the readme removing the Experimental language.  This repo still belongs in the CF incubator and we don't yet consider it GA.  That said, we do encourage expanded use with the understanding that we're continuing to add functionality and make changes that could impact scripting setups, etc.  Thank you for the suggestion!
