### ISSUE TITLE
Publish compiled binaries

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-incubator/uaa-cli#4]
For example, as github release artifacts like https://github.com/cloudfoundry/cli or to s3 like https://github.com/cloudfoundry/bosh-cli.

**Comment by drnic** [comment]
Bump.

**Comment by DennisDenuto** [comment]
fyi: We have added shipit job to publish a new release:
https://github.com/cloudfoundry-incubator/uaa-cli/releases/tag/0.0.1

We still need to make changes to attach the binaries / notes to the GH release

**Comment by drnic** [comment]
For anyone looking for linux/darwin binaries, plus homebrew/debian packages, try out a placeholder solution for now https://github.com/starkandwayne/uaa-cli-releases

**Comment by dbeneke** [comment]
Compiled binaries are available here: https://github.com/cloudfoundry-incubator/uaa-cli/releases
