### ISSUE TITLE
Using concourse to retrive the lastest version of uaa-cli returns 0.0.1

### ISSUE THREAD

**Issue by Houlistonm** [cloudfoundry-incubator/uaa-cli#43]
The url https://github.com/cloudfoundry-incubator/uaa-cli/releases/latest redirects to tag/release 0.0.1.  Please update the repo to point to the newest release.

Adding a `pre_release: true` to the concourse/github-release for uaa-cli allows me to work around the issue.

**Comment by dbeneke** [comment]
We've stopped releasing as 'pre-release' which should address the issue.  The latest version should be listed as the 'latest release' and not give you the same problem.
