### ISSUE TITLE
user creation shouldn't require givenname and familyname flags

### ISSUE THREAD

**Issue by paulczar** [cloudfoundry-incubator/uaa-cli#45]
In the ruby based uaa client you need username, password, email,  in this new go version you also need family name and given name. This will make it harder to update automation scripts using it.  Also not every user needs two names ( or any! ), for example robot users, also while rare some people only have one name.

ruby:
```
uaac user add test -p test --emails test@here.com
user account successfully added
```

go:
```
/tmp/uaa-linux-amd64-0.8.0 create-user test -p test --email test@here.com
Missing argument `familyName` must be specified. 

```

**Comment by dbeneke** [comment]
This change is included in the recent 0.10.0 release.
