### ISSUE TITLE
Name proposal: Guac

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/uaa-cli#5]
![screen shot 2018-04-23 at 10 56 01 am](https://user-images.githubusercontent.com/108/39144223-fd6068f6-46e4-11e8-8eb9-ea5c197037f2.png)

**Comment by cppforlife** [comment]
pls pls pls keep it as `uaa-cli`. all these fancy names confuse people about purpose of these tools.

**Comment by jhamon** [comment]
This project actually began with the name [guac](https://github.com/cloudfoundry-incubator/uaa-cli/commit/8e32c10d7b6e9a8dd6166540123c266eb2443642). We decided early to change to uaa-cli to follow the pattern laid out by [bosh](https://github.com/cloudfoundry/bosh-cli) and [credhub](https://github.com/cloudfoundry-incubator/credhub-cli), which is to have the cli name consistent with the product name and the repo name `<PRODUCT>-cli`. I think consistency across the Cloud Foundry ecosystem is important for discoverability.
