### ISSUE TITLE
uaa-cli should return nonzero exit code for failed UAA requests

### ISSUE THREAD

**Issue by aashah** [cloudfoundry-incubator/uaa-cli#9]
Currently, this has been allowing faulty requests to go through CI pipelines, and we've had to do some manual error handling.

I'm not sure what other clis have done as far as cloudfoundry cli convention goes.

**Comment by tylerschultz** [comment]
@dbeneke: Friendly bump, we ran into this problem. We were using `uaa-cli curl` in a bosh errand script and when the curl response was a non successful http code, the cli exited with `0` which allowed the script to keep running. This caused a problem for a real CF production environment. We went ahead and reproduced the issue on the latest version of the cli (0.8.0) to confirm that it has not been fixed yet.

**Comment by dbeneke** [comment]
Pulled out of the incubator back into public backlog.  Will prioritize for play.

**Comment by dbeneke** [comment]
This change was included in the 0.9.0 release.
